### ISSUE TITLE
Submit my Problem Statement

### ISSUE THREAD

**Issue by JohnErnsthausen** [JohnErnsthausen/roc#1]
Hello @smiths, Please find my ProblemStatement document in the agreed upon directory.

**Comment by smiths** [comment]
@JohnErnsthausen, your problem statement looks good.  I only have a few comments/questions:

- You barely introduced DAETS.  You should say what it is and include a reference
- How much does your proposed work depend on DAETS?  Can it be done independently?  It is easier if your work doesn't depend on DAETS.  If it does, then you might have to do a fork of the DAETS repo.
- It is unclear what is involved in broadening the applicability of TS methods in DAETS
- In your issues, for the convenience of the reviewer, please include the git commit hash that contains the file to be reviewed (or a link to the file)

Once you address the above comments, I'll officially approve your problem statement and close this issue.

**Comment by JohnErnsthausen** [comment]
@smiths I addressed your comments in Issue [#1](https://github.com/JohnErnsthausen/roc/issues/1#issue-705263479), with Git commit hash ade0ed. There is no need to mention DAETS in my Problem Statement as there is no dependency of my proposed problem for CSE 741 on DAETS. It may be interesting to understand that the deliverable of my proposed problem can be used in DAETS, but this is an aside for the work we are currently engaged.

**Comment by smiths** [comment]
Sounds good @JohnErnsthausen.   Your problem statement is approved.  :smile:

I have two minor comments for your consideration:

- The commit hash link didn't work in your message.  I was curious on why it didn't work.  It looks like you missed a character (ade0edc61616291a9c9b2cbb54a12bb84a3b49ef)
-  You have a long preamble to your tex file.  If you are going to use this in other tex files, it would make sense to add it to the `Common.tex` file (or something similar) and include it.  This will make your tex code maintenance easier.
